---
title: "Histórico das aulas do curso"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE}
source("setup_knitr.R")
```

- **03/02**:
  - Pesquisa reproduzível
    [ [HTML](http://leg.ufpr.br/~fernandomayer/pesqrep-eco/) |
    [PDF](http://leg.ufpr.br/~fernandomayer/pesqrep-eco/pesqrep-eco.pdf)
    ] e introdução às ferramentas do curso
  - Discussão do formulário pré-disciplina e exemplos pontuais
    - O R como linguagem de memória RAM, boas práticas para computação
      científica e estilos de código (*coding standards*) podem ser
      encontrados nessa página [HTML](computacao-cientifica.html).
  - Funções, objetos e classes (Parte I)
    [HTML](http://cursos.leg.ufpr.br/ce089/objetos-classes.html).
  - [Script](scripts/script_dia1.R) feito em aula.
- **04/02**:
  - Funções, objetos e classes (Parte II)
    [HTML](http://cursos.leg.ufpr.br/ce089/objetos-classes.html).
  - [Script](scripts/script_aula2.R) feito em aula.
- **05/02**:
  - Indexação e seleção condicional
    [HTML](http://cursos.leg.ufpr.br/ce089/indexacao-selecao.html).
  - Programando com dados
    [HTML](http://cursos.leg.ufpr.br/ce089/programacao.html).
  - Pesquisa reproduzível
    - Instalar os pacotes
      - `install.packages(c("knitr", "rmarkdown", "bookdown", "xtable", "remotes"))`
    - Literate programming
      [HTML](http://cursos.leg.ufpr.br/prr/capLitProg.html).
    - LaTeX, Markdown e Pandoc
      [HTML](http://cursos.leg.ufpr.br/prr/capMarkdown.html).
    - Documentos dinâmicos
      [HTML](http://cursos.leg.ufpr.br/prr/capDocDin.html).
    - Arquivo [ZIP](misc/docdin.zip) com diversos exemplos.
    - Exemplo de documentos personalizados:
      [legtheme](https://github.com/leg-ufpr/legtheme)
      - `remotes::install_github("leg-ufpr/legtheme")`
- **06/02**:
  - Técnicas de programação (*benchmarking*, *profiling*, *debugging*,
    *error handling*)
    [HTML](http://cursos.leg.ufpr.br/ce089/slides/01_tecnicas.html).
  - Pacotes e [renv](https://rstudio.github.io/renv/articles/renv.html).
- **07/02**:
  - Apresentações.
